[en]
  languageName = "English"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"

[de]
  languageName = "Deutsch"
  weight = 15
  [de.params]
    languageISO = "DE"
    languageTag = "de-DE"

[it]
  languageName = "Italian"
  weight = 15
  [it.params]
    languageISO = "IT"
    languageTag = "it-IT"
