[en]
  languageName = "English"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"

[it]
  languageName = "Italiano"
  weight = 15
  [it.params]
    languageISO = "IT"
    languageTag = "it-IT"
